// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from DemoLib/some_package.

#pragma once

#include <DemoLib/some_package/a.hpp>
#include <DemoLib/some_package/b.hpp>
