name: Generate Doxygen Documentation

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Create output directory
      run: >
        mkdir out

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: './doxyfile'

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './out/doxygen/html'
